# Generated by Django 2.0.2 on 2018-03-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='service_type',
        ),
        migrations.AddField(
            model_name='areasservices',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.ServiceArea'),
        ),
        migrations.AddField(
            model_name='areasservices',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.ServiceType'),
        ),
        migrations.AlterUniqueTogether(
            name='areasservices',
            unique_together={('area', 'service_type')},
        ),
    ]
